### ISSUE TITLE
poetry fail to install directly via git

### ISSUE THREAD

**Issue by ninyawee** [uezo/aiolinebot#2]
```
poetry add git+https://github.com/CircleOnCircles/aiolinebot.git#put-missing

  PackageInfoError

  Unable to determine package info for path: C:\Users\n2\AppData\Local\Temp\pypoetry-git-aiolinebo_u6ztofg

  Fallback egg_info generation failed.

  Command C:\Users\n2\AppData\Local\Temp\tmpwkp710lo\.venv\Scripts\python.exe setup.py egg_info errored with the following return code 1, and output:
  Traceback (most recent call last):
    File "setup.py", line 2, in <module>
      from aiolinebot import __version__
    File "C:\Users\n2\AppData\Local\Temp\pypoetry-git-aiolinebo_u6ztofg\aiolinebot\__init__.py", line 1, in <module>
      from linebot import __version__ as linebot_version
  ModuleNotFoundError: No module named 'linebot'

  at ~\.poetry\lib\poetry\inspection\info.py:502 in _pep517_metadata
      498│                 try:
      499│                     venv.run("python", "setup.py", "egg_info")
      500│                     return cls.from_metadata(path)
      501│                 except EnvCommandError as fbe:
    → 502│                     raise PackageInfoError(
      503│                         path, "Fallback egg_info generation failed.", fbe
      504│                     )
      505│                 finally:
      506│                     os.chdir(cwd.as_posix())
```

**Comment by uezo** [comment]
Hi @CircleOnCircles ,
I'm sorry for my late reply🙇‍♀️
Are you sure that you've already installed linebot-sdk-python to the venv you are to install aiolinebot?

**Comment by ninyawee** [comment]
yep

**Comment by ninyawee** [comment]
but let me reproduce again. by the way, `linebot-sdk-python` is the dependency of `aiolinebot` already isn't it?

**Comment by uezo** [comment]
@CircleOnCircles Thank you to retry it again. Yes, `aiolinebot` depends on `linebot-sdk-python`.

**Comment by ninyawee** [comment]
The issue is gone now.
